version: '3.8'

services:
  ml-api:
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  open-webui:
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-your-production-secret-key}
      - OLLAMA_BASE_URL=http://ml-api:8000
      - DEFAULT_MODELS=gpt-3.5-turbo
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 